#' Read in a marginal distribution
#' 
#' Create a dataframe from the distribution file generated by ASR.jar using marginal inference
#' 
#' @param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#' @param distrib_file distribution file generated by ASR.jar
#' 
#' @return a dataframe with three columns representing the distribution at each column in the alignment. Formatted to
#' be passed to \code{\link{plot_distrib}}.\cr
#' distribDF$AA\cr
#' distribDF$Column \cr
#' distribDF$Probability \cr
#' #Example\cr
#' distribDF[1, ] = "A", "5", "0.9" - An A in column 5 has a probability of 0.9\cr
#' 
#' @examples
#'data(asrStructure)
#' 
#' read_distrib(asrStructure)
#' #retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' read_distrib(NULL, distrib_file = id_distribution) #if you want to specify your own file
#' 
#' @export

read_distrib <- function(asrStructure, distrib_file = NULL) {
  
  if (!is.null(asrStructure)) {
    if (typeof(asrStructure) != "list") {
      stop(paste("The input for asrStructure: ", asrStructure, ", is not a list therefore not a valid input", sep = ""))
    }
    distrib = asrStructure$loadedFiles$distribution
    if (is.null(distrib)) {
      stop("asrStructure does not contain required distribution file.
           To generate the required files and structures to use this function 
           you will need to run runASR() using Marginal inference.")
    }
  } else {
    if(is.null(distrib_file)) {
      stop("You have not provided an asrStructure or specified distrib_file")
    } else if (!file.exists(distrib_file)) {
      stop(paste(distrib_file, " does not exist"))
    } else {
      distrib <- read.table(distrib_file, header = T, row.names = 1, sep = "\t")
      ##How do you check if this is the right file?##
    }
  }
  
  colnames(distrib) <- seq(1, dim(distrib)[2], 1)
  mat <- matrix(rep(0, 3*(dim(distrib)[1] * dim(distrib)[2])), ncol = 3, nrow = (dim(distrib)[1] * dim(distrib)[2]))
  rows <- rownames(distrib)
  cols <- colnames(distrib)
  matCounter = 1
  for (i in seq(1, dim(distrib)[1], 1)) {
    for (j in seq(1, dim(distrib)[2], 1)) {
      mat[matCounter, 1] = rows[i]
      mat[matCounter, 2] = cols[j]
      mat[matCounter, 3] = distrib[i, j]
      matCounter = matCounter + 1
    }
  }
  df <- data.frame(mat[,1], mat[,2],as.numeric(as.character(mat[,3])))
  colnames(df) <- c("AA", "Column", "Probability")
  df
  }

#'Plot marginal distrib
#'
#'Displays a heatmap showing the probabilities of each amino acid across all columns in the alignment
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param distribDF a dataframe created by \code{\link{read_distrib}}
#'@param columns a vector containing the column numbers of interest. By default = NULL and all columns are displayed
#'@param aas a vector containing the amino acids of interest. By default = NULL and all amino acids are displayed
#'@param type how the distribution should be displayed, default plain text.
#'@param colour only available in conjunction with type="logo" to specify the colour scheme for AAs. options: "clustal", "zappo", "taylor"
#'options: "colour", "text", "logo", "colouredText"
#'NOTE: "logo" uses \code{\link{plot_logo_distrib}}
#'
#'@return plots a matrix of amino acid probability at given columns in alignment
#'
#'@examples
#'data(asrStructure)
#'
#'plot_distrib(asrStructure) #if you want to use the information stored in the structure
#'
#'#To change the display of the plot
#'plot_distrib(asrStructure, type = "colour")
#'plot_distrib(asrStructure, type = "text")
#'plot_distrib(asrStructure, type = "logo")
#'plot_distrib(asrStructure, type = "colouredText")
#'
#'
#'#if you want to use a specific set of data
#'#' #retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#'distribDF <- read_distrib(NULL, id_distribution)
#'plot_distrib(NULL, distribDF = distribDF)
#'
#'#to specify particular columns and AAs to include in figure
#'columns = c(4,5,6,7)
#'aas = c("G", "P")
#'
#'plot_distrib(asrStructure, columns = columns)
#'plot_distrib(asrStructure, aas = aas)
#'plot_distrib(asrStructure, columns = columns, aas = aas)
#'#OR
#'plot_distrib(NULL, distribDF = distribDF, columns = columns)
#'
#'@export

plot_distrib <- function(asrStructure, distribDF=NULL, type="colouredText", colour=NULL, columns=NULL, aas = NULL) {
  
  Probability <- NULL; rm(Probability);
  Column <- NULL; rm(Column);
  AA <- NULL; rm(AA);
  
  if (type == "logo") {
    pl <- plot_logo_distrib(asrStructure, colour=colour, columns = columns)
    return(pl)
  } else {
    if (!is.null(colour)) {
      print("Your colour choice has been ignored as colour is an argument only available when type='logo' for plot_distrib()")
    }
  }
  
  distribDF <- dfError(asrStructure, "distribProbs", distribDF, c("Column", "Probability", "AA"), "Marginal")
  
  if (!is.null(columns)) {
    distribDF <- distribDF[distribDF$Column %in% columns, ]
    distribDF$Column <- factor(distribDF$Column)
  }
  if (!is.null(aas)) {
    distribDF <- distribDF[distribDF$AA %in% aas, ]
    distribDF$AA <- factor(distribDF$AA)
  }
  
  distribDF$Column <- factor(distribDF$Column, levels = as.character(sort(as.numeric(levels(distribDF$Column)))))
  distribDF$AA <- factor(distribDF$AA)
  
  if (type == "text") {
    ggplot2::ggplot(distribDF, ggplot2::aes(x=Column, y=AA, label=format(Probability, scientific=TRUE, nsmall=2, digits = 3))) + 
      ggplot2::geom_text(size = 2) + 
      ggplot2::geom_vline(xintercept=seq(1.5, length(levels(distribDF$Column))-0.5, 1), colour='black', size = 0.1) + 
      ggplot2::theme_bw()+ggplot2::theme(panel.grid.major = ggplot2::element_blank())+
      ggplot2::theme(text = ggplot2::element_text(size=12),axis.text.x=ggplot2::element_text(angle = 45, hjust=1))
  } else if (type == "colour") {
    ggplot2::ggplot(distribDF, ggplot2::aes(x=Column, y=AA)) + 
      ggplot2::geom_tile(ggplot2::aes(fill = Probability), colour = "white") + 
      ggplot2::scale_fill_gradient(low="Red", high="Green") + 
      ggplot2::theme_bw()+
      ggplot2::theme(text = ggplot2::element_text(size=24),axis.text.x=ggplot2::element_text(angle = 45, hjust=1))
  } else if (type == "colouredText") {
    ggplot2::ggplot(distribDF, ggplot2::aes(x=Column, y=AA, label=format(Probability, scientific=TRUE, nsmall=2, digits = 3), colour = Probability)) + 
      ggplot2::geom_text(size = 2) + 
      ggplot2::scale_colour_gradient(low="Red", high="Green") + 
      ggplot2::geom_vline(xintercept=seq(1.5, length(levels(distribDF$Column))-0.5, 1), colour='black', size = 0.1) + 
      ggplot2::theme_bw()+ggplot2::theme(panel.grid.major = ggplot2::element_blank())+
      ggplot2::theme(text = ggplot2::element_text(size=12),axis.text.x=ggplot2::element_text(angle = 45, hjust=1))
  } else {
    stop("Invalid type for plot_distrib")
  }
}

#'Save marginal distrib plot
#'
#'Saves a heatmap showing the probabilities of each amino acid across all columns in the alignment
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param distribDF a dataframe created by \code{\link{read_distrib}}
#'@param type how the distribution should be displayed, default plain text.
#'options: "colour", "text", "logo", "colouredText"
#'@param colour only available in conjunction with type="logo" to specify the colour scheme for AAs. options: "clustal", "zappo", "taylor"
#'@param columns a vector containing the column numbers of interest. By default = NULL and all columns are displayed
#'@param aas a vector containing the amino acids of interest. By default = NULL and all amino acids are displayed
#'@param format specifies what format the figure should be saved in. Options: "pdf" or "png"
#'@param name what name would you like the figure saved under?
#'
#'@examples
#'data(asrStructure)
#'
#'save_distrib(asrStructure) #if you want to use the information stored in the structure
#'
#'#if you want to use a specific set of data
#'#' #retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#'distribDF <- read_distrib(NULL, id_distribution)
#'save_distrib(NULL, distribDF = distribDF)
#'
#'#to specify particular columns and AAs to include in figure
#'columns = c(4,5,6,7)
#'aas = c("G", "P")
#'
#'save_distrib(asrStructure, columns = columns)
#'save_distrib(asrStructure, aas = aas)
#'save_distrib(asrStructure, columns = columns, aas = aas)
#'#OR
#'save_distrib(NULL, distribDF = distribDF, columns = columns)
#'
#'save_distrib(asrStructure, format = "png", name = "new_name")
#'
#'@export

save_distrib <- function(asrStructure, distribDF=NULL, type = "colouredText", colour=NULL,columns=NULL, aas = NULL, format = "pdf", name = NULL) {
  
  distribDF <- dfError(asrStructure, "distribProbs", distribDF, c("Column", "Probability", "AA"), "Marginal")
  
  if (type =="logo") {
    if (is.null(asrStructure)) {
      stop(paste("Cannot access heights for logo without asrStructure. Providing seqDF alone is not adequate."))
    } else {
      gg <- plot_logo_distrib(asrStructure, colour = colour, columns = columns)
    }
  } else if (type =="colour" || type == "colouredText" || type == "text") {
     gg <- plot_distrib(NULL,distribDF=distribDF,type = type,colour=colour,columns = columns)
  } else {
    stop("Invalid type for plot_aln")
  }
  
  if(is.null(name)) {
    if (is.null(asrStructure)) {
      name = "distribution"
    } else {
      name = asrStructure$fileNames$Distrib
    }
  }
  
  y = length(unique(levels(distribDF$AA)))
  x = length(unique(levels(distribDF$Column)))
  if (format == "pdf") {
    if (grepl("ext", type)) {
      w = (x * 0.400) + (1/(x/100))
      h = (y * 0.050) + 5.473
    } else {
      w = (x * 0.360) + (1/(x/50))
      h = (y * 0.250) + 5.473
    }
    pdf(paste(name, "_plot.", format, sep=""), width=w, height=h)
    print(gg)
    dev.off()
    return(paste("Plot saved as:", name, "_plot.", format, sep=""))
  } else if (format == "png") {
    w = (x * 40) + 200
    h = (y * 28) + 200
    png(paste(name, "_plot.", format, sep=""), width=w, height=h)
    print(gg)
    dev.off()
    return(paste("Plot saved as:", name, "_plot.", format, sep=""))
  } else {
    stop("Invalid format for save_distrib")
  }
}
