#' Read in a fasta alignment file
#' 
#' Takes a fasta alignment file generate by ASR.jar and formats it into 
#' a dataframe that can be read by other functions (e.g. \code{\link{get_seq_df}})
#' 
#' @param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#' @param aln_file aln file generated by ASR.jar
#' 
#' @return a dataframe with three columns representing the sequences stored in the fasta file. Formatted to
#' be passed to \code{\link{get_seq_df}}.\cr
#' fastaDF$Label - label/id of sequence\cr
#' fastaDF$Newick - newick string with current node/sequence as root. NULL if extant\cr
#' fastaDF$Sequence - a single string representing the sequence\cr
#' #Example\cr
#' fastaDF[1,] = "N4_", "(extant_3:0.05,extant_4:0.05)N4_:0.05;", "G-PPGPKT"\cr
#' 
#' @examples
#'data(asrStructure)
#'
#' read_fasta(asrStructure)
#'
#' #if you want to use a specific set of data 
#'#retrieve example file stored in the package
#'fasta_file <- system.file("extdata", "runASR_aln_full.fa", package="ASR")
#' #alternatively, specify the filename as a string
#' #fasta_file <- "id_aln_full.fa"
#' 
#' read_fasta(NULL, aln_file = fasta_file) # if you want to use a specific file
#' 
#' @export

read_fasta <- function(asrStructure, aln_file=NULL ) {
  
  if (!is.null(asrStructure)) {
    fastaFile = asrStructure$loadedFiles$alignment
    if(is.null(fastaFile)) {
      stop("asrStructure does not contain required fasta file/alignment information. 
            To generate the required files and structures to use this function 
            you will need to run runASR() using Joint inference.")
    }
  } else {
    if(is.null(aln_file)) {
      stop("You have not provided an asrStructure or specified aln_file")
    } else if (!file.exists(aln_file)) {
      stop("aln_file does not exist")
    } else {
      fastaFile <- read.table(aln_file, header = F, sep = "\n")
      ##How do you check if this is the right file?##
    }
  }
  
  fastaString = ""
  for (i in seq(1, dim(fastaFile)[1], 1)) {
    if (grepl(">",as.character(fastaFile[i,]))) {
      fastaString = paste(fastaString, fastaFile[i,], sep="\t")
    } else if (grepl(">",as.character(fastaFile[i-1,]))) {
      fastaString = paste(fastaString, " ", fastaFile[i,], sep="")
    } else {
      fastaString = paste(fastaString, fastaFile[i,], sep="")
    }
  }
  fastaSplit <- strsplit(fastaString, "\t")
  mat <- matrix(rep(0, 3*(length(fastaSplit[[1]])-1)), ncol=3, nrow=length(fastaSplit[[1]])-1)
  counter = 1
  for (i in seq(2, length(fastaSplit[[1]]), 1)) {
    faEntry <- strsplit(fastaSplit[[1]][i], " ")
    if (length(faEntry[[1]]) == 3) {
      mat[counter, 1] <- gsub(">", "", faEntry[[1]][1])
      mat[counter, 2] <- faEntry[[1]][2]
      mat[counter, 3] <- faEntry[[1]][3]
    } else if (length(faEntry[[1]]) == 2){
      mat[counter, 1] <- gsub(">", "", faEntry[[1]][1])
      mat[counter, 2] <- "null"
      mat[counter, 3] <- faEntry[[1]][2]
    }
    counter = counter + 1
  }
  df <- data.frame(as.character(mat[,1]), as.character(mat[,2]), as.character(mat[,3]))
  colnames(df) <- c("Label", "Newick", "Sequence")
  df
}