#'Calculate the height of letters in columns
#'
#'Takes the distribution data frame and calculates a logo height for each amino acid in each column 
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param distribDF the dataframe generated by \code{\link{read_distrib}}
#'@param alphabet can be one of AA, DNA or RNA
#'
#'@return a dataframe with three columns representing the height of each AA at each column in the alignment. Formatted to
#' be passed to \code{\link{plot_logo}} or \code{\link{save_logo}}.\cr
#' heightDF$AA\cr
#' heightDF$Column \cr
#' heightDF$Height \cr
#' #Example\cr
#' heightDF[1, ] = "A", "5", "1.17" - An A in column 5 has a height of 1.17\cr
#' 
#' @examples
#'data(asrStructure)
#' 
#' logo_height(asrStructure)
#' 
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#' distribDF <- read_distrib(NULL, distrib_file = id_distribution)
#' logo_height(NULL, distribDF = distribDF) #if you want to specify your own file
#'
#' @export

logo_height <- function(asrStructure, distribDF = NULL, alphabet = "AA") {

  shannon <- function(x) {
    x = as.numeric(x)
    x = x * log2(x)
    x
  }
  
  if (!is.null(asrStructure)) {
    distribDF <- asrStructure$distribProb
    if (is.null(distribDF)) {
      stop("asrStructure does not contain required distribution information")
    }
  } else {
    if(is.null(distribDF)) {
      stop("You have not provided an asrStructure or specified distribDF")
    } else {
      cols <- colnames(distribDF)
      if (!("Column" %in% cols && "AA" %in% cols && "Probability" %in% cols)) {
        stop("The dataframe provided as distribDF is not correctly formatted. See read_distrib()")
      }
    }
  }
  
  if (alphabet == "AA") {
    letters = c("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y")
  } else if (alphabet == "DNA") {
    letters = c("A", "T", "G", "C")
  } else if (alphabet == "RNA") {
    letters = c("A", "U", "G", "C")
  } else {
    stop("Invalid alphabet for logo_height")
  }  

  distribDF <- distribDF[!is.na(distribDF$Probability), ] ##Remove NAs
  distribDF$Column <- factor(distribDF$Column)
  cols <- levels(distribDF$Column)
  
  sampleCorrection <- (1/log(2)) * ((length(letters) -1)/(2 * length(cols)))
  
  fullHeights <- rep(0, length(cols))
  for (i in seq(1, length(cols), 1)) {
    probs <- distribDF[distribDF$Column == cols[i], ]$Probability
    hi <- -sum(sapply(probs, shannon))
    if (alphabet == "AA") {
      fullHeight <- log2(20) - (hi + sampleCorrection)
    } else {
      fullHeight <- 2 - (hi + sampleCorrection)
    }
    distribDF[distribDF$Column == cols[i], 3] <- distribDF[distribDF$Column == cols[i], 3] * fullHeight
  }

  colnames(distribDF) <-  c("AA", "Column", "Height")
  distribDF
  
}

#'Plot amino acid heights as a barchart to represent logo
#'
#'Takes the distribution height data frame and plot a barchart for each column using the calculated heights
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param heightDF a data frame containing heights generated by \code{\link{logo_height}}
#'@param colour the colour scheme to be used to colour AAs
#'@param columns a vector containing the column numbers of interest. By default = NULL and all columns are displayed
#'
#'@return plots a variation on a sequence logo based on distribDF of AAs in columns
#'
#'@examples
#'data(asrStructure)
#'
#'plot_logo(asrStructure) #if you want to use the information stored in the structure
#'
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#'distribDF <- read_distrib(NULL, distrib_file = id_distribution)
#'heightDF <- logo_height(NULL, distribDF = distribDF)
#'plot_logo(NULL, heightDF = heightDF)
#'
#'#to specify particular columns to include in figure
#'columns = c(3,4,5,6)
#'
#'plot_logo(asrStructure, columns = columns)
#'#OR
#'plot_logo(NULL, heightDF = heightDF, columns = columns)
#'
#'#to change the colouring of AAs
#'plot_logo(asrStructure, colour = "clustal")
#'plot_logo(asrStructure, colour = "zappo")
#' 
#'@export

plot_logo <- function(asrStructure, heightDF = NULL, colour = "taylor", columns=NULL) {
  
  Height <- NULL; rm(Height);
  Column <- NULL; rm(Column);
  AA <- NULL; rm(AA);
  
  if (!is.null(asrStructure)) {
    heightDF <- asrStructure$distribHeight
    if (is.null(heightDF)) {
      stop("asrStructure does not contain required height information
            To generate the required files and structures to use this function 
            you will need to run runASR() using Marginal inference.")
    }
  } else {
    if(is.null(heightDF)) {
      stop("You have not provided an asrStructure or specified heightDF")
    } else {
      cols <- colnames(heightDF)
      if (!("Column" %in% cols && "AA" %in% cols && "Height" %in% cols)) {
        stop("The dataframe provided as heightDF is not correctly formatted. See logo_height()")
      }
    }
  }
  
  if (!is.null(columns)) {
    heightDF <- heightDF[heightDF$Column %in% columns, ]
    heightDF$Column <- factor(heightDF$Column)
  }
  
  heightDF$Column <- factor(heightDF$Column, levels = as.character(sort(as.numeric(levels(heightDF$Column)))))
  heightDF$AA <- factor(heightDF$AA)
  
  if (colour == "clustal") {
    colourPalette = colours_clustal(levels(heightDF$AA))
  } else if (colour == "zappo") {
    colourPalette = colours_zappo(levels(heightDF$AA))
  } else if (colour == "taylor") {
    colourPalette = colours_taylor(levels(heightDF$AA))
  } else {
    stop("Invalid colour choice for plot_aln()")
  }
  
  ggplot2::ggplot(heightDF, ggplot2::aes(x=Column, y=Height)) + 
    ggplot2::geom_bar(ggplot2::aes(fill = AA), stat = "identity") + 
    ggplot2::scale_fill_manual(values = colourPalette) + 
    ggplot2::theme_bw()+
    ggplot2::theme(text = ggplot2::element_text(size=30),axis.text.x=ggplot2::element_text(angle = 45, hjust=1))
}

#'Save amino acid heights as a barchart to represent logo
#'
#'Takes the distribution height data frame and plots then saves a barchart for each column using the calculated heights
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param heightDF a data frame containing heights generated by \code{\link{logo_height}}
#'@param colour the colour scheme to be used to colour AAs
#'@param columns a vector containing the column numbers of interest. By default = NULL and all columns are displayed
#'@param format specifies what format the figure should be saved in. Options: "pdf" or "png"
#'@param name what name would you like the figure saved under?
#'
#'@return plots a variation on a sequence logo based on probabilities of AAs in columns
#'
#'@examples
#'data(asrStructure)
#'
#'save_logo(asrStructure) #if you want to use the information stored in the structure
#'
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#' distribDF <- read_distrib(NULL, distrib_file = id_distribution)
#' 
#'heightDF <- logo_height(NULL, distribDF = distribDF)
#'save_logo(NULL, heightDF = heightDF)
#'
#'#to specify particular columns to include in figure
#'columns = c(3,4,5,6)
#'
#'save_logo(asrStructure, columns = columns)
#'#OR
#'save_logo(NULL, heightDF = heightDF, columns = columns)
#'
#'#to change the colouring of AAs
#'save_logo(asrStructure, colour = "clustal")
#'
#'save_logo(asrStructure, format = "png", name = "new_name")
#' 
#'@export

save_logo <- function(asrStructure, heightDF = NULL, colour = "taylor", columns=NULL, format = "pdf", name = NULL) {
  
  Height <- NULL; rm(Height);
  Column <- NULL; rm(Column);
  AA <- NULL; rm(AA);
  
  if (!is.null(asrStructure)) {
    heightDF <- asrStructure$distribHeight
    if (is.null(heightDF)) {
      stop("asrStructure does not contain required height information
           To generate the required files and structures to use this function 
           you will need to run runASR() using Marginal inference.")
    }
  } else {
    if(is.null(heightDF)) {
      stop("You have not provided an asrStructure or specified heightDF")
    } else {
      cols <- colnames(heightDF)
      if (!("Column" %in% cols && "AA" %in% cols && "Height" %in% cols)) {
        stop("The dataframe provided as heightDF is not correctly formatted. See logo_height()")
      }
    }
  }
  
  if (!is.null(columns)) {
    heightDF <- heightDF[heightDF$Column %in% columns, ]
    heightDF$Column <- factor(heightDF$Column)
  }
  
  heightDF$Column <- factor(heightDF$Column, levels = as.character(sort(as.numeric(levels(heightDF$Column)))))
  heightDF$AA <- factor(heightDF$AA)
  
  if (colour == "clustal") {
    colourPalette = colours_clustal(levels(heightDF$AA))
  } else if (colour == "zappo") {
    colourPalette = colours_zappo(levels(heightDF$AA))
  } else if (colour == "taylor") {
    colourPalette = colours_taylor(levels(heightDF$AA))
  } else {
    stop("Invalid colour choice for plot_aln()")
  }
  
  gg <- ggplot2::ggplot(heightDF, ggplot2::aes(x=Column, y=Height)) + 
    ggplot2::geom_bar(ggplot2::aes(fill = AA), stat = "identity") + 
    ggplot2::scale_fill_manual(values = colourPalette) + 
    ggplot2::theme_bw()+
    ggplot2::theme(text = ggplot2::element_text(size=24),axis.text.x=ggplot2::element_text(angle = 45, hjust=1))
  
  if(is.null(name)) {
    if (is.null(asrStructure)) {
      name = "distribution_logo"
    } else {
      name = paste(asrStructure$fileNames$Distrib, "_logo", sep = "")
    }
  }
  
  x = length(unique(levels(heightDF$Column)))
  if (format == "pdf") {
    w = (x * 0.360) + (1/(x/80))
    pdf(paste(name, "_plot.", format, sep=""), width=w, height=10)
    print(gg)
    dev.off()
    return(paste("Plot saved as:", name, "_plot.", format, sep=""))
  } else if (format == "png") {
    w = (x * 40) + 200
    png(paste(name, "_plot.", format, sep=""), width=w, height=1000)
    print(gg)
    dev.off()
    return(paste("Plot saved as:", name, "_plot.", format, sep=""))
  } else {
    stop("Invalid format for save_distrib")
  }
}

