#'Calculate the height of letters in columns
#'
#'Takes the distribution data frame and calculates a logo height for each amino acid in each column 
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param distribDF the dataframe generated by \code{\link{read_distrib}}
#'@param alphabet choice of AA, DNA or RNA
#'
#'@return a dataframe with three columns representing the height of each AA at each column in the alignment. Formatted to
#' be passed to \code{\link{plot_logo_distrib}}\cr
#' heightDF$AA\cr
#' heightDF$Column \cr
#' heightDF$Height \cr
#' #Example\cr
#' heightDF[1, ] = "A", "5", "1.17" - An A in column 5 has a height of 1.17\cr
#' 
#' @examples
#'data(asrStructure)
#' 
#' logo_height_distrib(asrStructure)
#' 
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#' distribDF <- read_distrib(NULL, distrib_file = id_distribution)
#' logo_height_distrib(NULL, distribDF = distribDF) #if you want to specify your own file
#'
#' @export

logo_height_distrib <- function(asrStructure, distribDF = NULL, alphabet = "AA") {

  shannon <- function(x) {
    x = as.numeric(x)
    x = x * log2(x)
    x
  }
  
  distribDF <- dfError(asrStructure, "distribProb", distribDF, c("Column", "AA", "Probability"), "Marginal")
  
  aa = c("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y")
  dna = c("A", "T", "G", "C")
  rna = c("A", "U", "G", "C")
  if ("U" %in% distribDF$AA) {
    alphabet = "RNA"
    letters = rna
  } else if (Reduce('&',dna %in% distribDF$AA) && length(levels(distribDF$AA)) <= 5) {
    alphabet = "DNA"
    letters = dna
  } else if (Reduce('&',aa %in% distribDF$AA) && length(levels(distribDF$AA)) > 5) {
    alphabet = "AA"
    letters = aa
  } else {
    print(paste("Having trouble detecting alphabet in hidden.logo_height_distrib. Using default value for alphabet: ", alphabet, sep=""))
    if (alphabet == "AA") {
      letters = aa
    } else if (alphabet == "DNA") {
      letters = dna
    } else if (alphabet == "RNA") {
      letters = rna
    } else {
      stop("Invalid alphabet for hidden.logo_height")
    }  
  }  

  distribDF <- distribDF[!is.na(distribDF$Probability), ] ##Remove NAs
  distribDF$Column <- factor(distribDF$Column)
  cols <- levels(distribDF$Column)
  
#   sampleCorrection <- (1/log(2)) * ((length(letters) -1)/(2 * length(cols)))
  
  fullHeights <- rep(0, length(cols))
  for (i in seq(1, length(cols), 1)) {
    probs <- distribDF[distribDF$Column == cols[i], ]$Probability
    hi <- -sum(sapply(probs, shannon))
    if (alphabet == "AA") {
#       fullHeight <- log2(20) - (hi + sampleCorrection)
      fullHeight <- log2(20) - hi
    } else {
#       fullHeight <- 2 - (hi + sampleCorrection)
      fullHeight <- 2 - hi
    }
    distribDF[distribDF$Column == cols[i], 3] <- distribDF[distribDF$Column == cols[i], 3] * fullHeight
  }

  colnames(distribDF) <-  c("AA", "Column", "Height")
  distribDF
  
}

#'Plot amino acid heights as a barchart to represent logo
#'
#'Takes the distribution height data frame and plot a barchart for each column using the calculated heights
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param heightDF a data frame containing heights generated by \code{\link{logo_height_distrib}}
#'@param colour the colour scheme to be used to colour AAs
#'@param columns a vector containing the column numbers of interest. By default = NULL and all columns are displayed
#'
#'@return plots a variation on a sequence logo based on distribDF of AAs in columns
#'
#'@examples
#'data(asrStructure)
#'
#'plot_logo_distrib(asrStructure) #if you want to use the information stored in the structure
#'
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#'distribDF <- read_distrib(NULL, distrib_file = id_distribution)
#'heightDF <- logo_height_distrib(NULL, distribDF = distribDF)
#'plot_logo_distrib(NULL, heightDF = heightDF)
#'
#'#to specify particular columns to include in figure
#'columns = c(3,4,5,6)
#'
#'plot_logo_distrib(asrStructure, columns = columns)
#'#OR
#'plot_logo_distrib(NULL, heightDF = heightDF, columns = columns)
#'
#'#to change the colouring of AAs
#'plot_logo_distrib(asrStructure, colour = "clustal")
#'plot_logo_distrib(asrStructure, colour = "zappo")
#' 
#'@export

plot_logo_distrib <- function(asrStructure, heightDF = NULL, colour = "taylor", columns=NULL) {
  
  Height <- NULL; rm(Height);
  Column <- NULL; rm(Column);
  AA <- NULL; rm(AA);
  
  heightDF <- dfError(asrStructure, "distribHeights", heightDF, c("Column", "AA", "Height"), "Marginal")
  
  if (!is.null(columns)) {
    heightDF <- heightDF[heightDF$Column %in% columns, ]
    heightDF$Column <- factor(heightDF$Column)
  }
  
  heightDF$Column <- factor(heightDF$Column, levels = as.character(sort(as.numeric(levels(heightDF$Column)))))
  heightDF$AA <- factor(heightDF$AA)
  if (is.null(colour)) {
    colour = "taylor"
  }
  if (colour == "clustal") {
    colourPalette = colours_clustal(levels(heightDF$AA))
  } else if (colour == "zappo") {
    colourPalette = colours_zappo(levels(heightDF$AA))
  } else if (colour == "taylor") {
    colourPalette = colours_taylor(levels(heightDF$AA))
  } else {
    stop("Invalid colour choice for plot_aln()")
  }
  
  ggplot2::ggplot(heightDF, ggplot2::aes(x=Column, y=Height)) + 
    ggplot2::geom_bar(ggplot2::aes(fill = AA), stat = "identity") + 
    ggplot2::scale_fill_manual(values = colourPalette) + 
    ggplot2::theme_bw()+
    ggplot2::theme(text = ggplot2::element_text(size=30),axis.text.x=ggplot2::element_text(angle = 45, hjust=1))
}
