#'Calculate the height of letters in columns
#'
#'Takes the distribution data frame and calculates a logo height for each amino acid in each column 
#'
#'@param asrStructure the named list returned by \code{\link{runASR}}, \code{\link{loadASR}} or \code{\link{reduce_alphabet}}. Set this to NULL
#'to specify other variables
#'@param distribDF the dataframe generated by \code{\link{read_distrib}}
#'@param alphabet an alphabet which represents the lettering of the distribution of interest
#'@param alphabetType choice of AA, DNA, RNA or User
#'
#'@return a dataframe with three columns representing the height of each AA at each column in the alignment. Formatted to
#' be passed to \code{\link{plot_logo_distrib}}\cr
#' heightDF$AA\cr
#' heightDF$Column \cr
#' heightDF$Height \cr
#' #Example\cr
#' heightDF[1, ] = "A", "5", "1.17" - An A in column 5 has a height of 1.17\cr
#' 
#' @examples
#'data(asrStructure)
#' 
#' logo_height_distrib(asrStructure)
#' 
#' alphabet <- c("H", "C", "N", "P", "R") #Order is irrelevant
#' logo_height_distrib(asrStructure, alphabet=alphabet)
#' 
#' #this method attempts to detect the alphabet but allows the user to specify
#' logo_height_distrib(asrStructure, alphabet="DNA")
#' 
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#' distribDF <- read_distrib(NULL, distrib_file = id_distribution)
#' logo_height_distrib(NULL, distribDF = distribDF) #if you want to specify your own file
#'
#' @export

logo_height_distrib <- function(asrStructure, distribDF = NULL, alphabet=NULL, alphabetType=NULL) {

  shannon <- function(x) {
    x = as.numeric(x)
    x = x * log2(x)
    x
  }
  
  distribDF <- dfError(asrStructure, "distribProbs", distribDF, c("Column", "AA", "Probability"), "Marginal")
  
  aa = c("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y")
  dna = c("A", "T", "G", "C")
  rna = c("A", "U", "G", "C")
  if (is.null(alphabetType)) {
    if (is.null(alphabet)) {
      print("No provided alphabetType or alphabet, attempting to detect alphabet")
      default = FALSE
      if ("U" %in% distribDF$AA) {
        alphabetType = "RNA"
        alphabet = rna
        print(paste("Detected alphabetType: ", alphabetType, ". Alphabet equal to: ", seq = ""))
        print(alphabet)
        print("If this is incorrect, please specify an alphabet or alphabet type")
      } else if (Reduce('&',dna %in% distribDF$AA) && length(levels(distribDF$AA)) <= 4) {
        alphabetType = "DNA"
        alphabet = dna
      } else if (Reduce('&',aa %in% distribDF$AA) && length(levels(distribDF$AA)) > 4) {
        alphabetType = "AA"
        alphabet = aa
      } else {
        default = TRUE
        print(paste("Having trouble detecting alphabet in hidden.logo_height_distrib. Using default value for alphabet: AA.
                    If this is incorrect, please specify an alphabet or alphabet type", sep=""))
        alphabet = aa
      }  
      if (!default) {
        print(paste("Detected alphabetType: ", alphabetType, ". Alphabet equal to: ", seq = ""))
        print(alphabet)
        print("If this is incorrect, please specify an alphabet or alphabet type")
      }
    } else {
      alphabetType = "User"
    }
  } else if (alphabetType == "AA") {
    alphabet = aa
  } else if (alphabetType == "DNA") {
    alphabet = dna
  } else if (alphabetType == "RNA") {
    alphabet = rna
  } else if (alphabetType == "User") {
    alphabet = alphabet
  } else {
    stop("Invalid alphabetType for hidden.logo_height")
  }  

  distribDF <- distribDF[!is.na(distribDF$Probability), ] ##Remove NAs
  distribDF$Column <- factor(distribDF$Column)
  cols <- levels(distribDF$Column)

  for (i in seq(1, length(cols), 1)) {
    probs <- distribDF[distribDF$Column == cols[i], ]$Probability
    entropy <- -sum(sapply(probs, shannon)) #calculate Shannon entropy
    infoContent <- log2(length(alphabet)) - entropy #calculate information content
    distribDF[distribDF$Column == cols[i], 3] <- distribDF[distribDF$Column == cols[i], 3] * infoContent #calculate height
  }

  colnames(distribDF) <-  c("AA", "Column", "Height")
  distribDF
  
}

#'Plot amino acid heights as a barchart to represent logo
#'
#'Takes the distribution height data frame and plot a barchart for each column using the calculated heights
#'
#'@param asrStructure the named list returned by \code{\link{runASR}}, \code{\link{loadASR}} or \code{\link{reduce_alphabet}}. Set this to NULL
#'to specify other variables
#'@param heightDF a data frame containing heights generated by \code{\link{logo_height_distrib}}
#'@param colour the colour scheme to be used to colour AAs
#'@param columns a vector containing the column numbers of interest. By default = NULL and all columns are displayed
#'
#'@return plots a variation on a sequence logo based on distribDF of AAs in columns
#'
#'@examples
#'data(asrStructure)
#'
#'plot_logo_distrib(asrStructure) #if you want to use the information stored in the structure
#'
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#' id_distribution <- system.file("extdata", "runASR_distribution.txt", package="ASR")
#' #alternatively, specify the filename as a string
#' #id_distribution <- "id_distribution.txt"
#' 
#'distribDF <- read_distrib(NULL, distrib_file = id_distribution)
#'heightDF <- logo_height_distrib(NULL, distribDF = distribDF)
#'plot_logo_distrib(NULL, heightDF = heightDF)
#'
#'#to specify particular columns to include in figure
#'columns = c(3,4,5,6)
#'
#'plot_logo_distrib(asrStructure, columns = columns)
#'#OR
#'plot_logo_distrib(NULL, heightDF = heightDF, columns = columns)
#'
#'#to change the colouring of AAs
#'plot_logo_distrib(asrStructure, colour = "clustal")
#'plot_logo_distrib(asrStructure, colour = "zappo")
#'plot_logo_distrib(asrStructure, colour = "mixed")
#' 
#'@export

plot_logo_distrib <- function(asrStructure, heightDF = NULL, colour = "taylor", columns=NULL) {
  
  Height <- NULL; rm(Height);
  Column <- NULL; rm(Column);
  AA <- NULL; rm(AA);
  
  heightDF <- dfError(asrStructure, "distribHeights", heightDF, c("Column", "AA", "Height"), "Marginal")
  
  if (!is.null(columns)) {
    heightDF <- heightDF[heightDF$Column %in% columns, ]
    heightDF$Column <- factor(heightDF$Column)
  }
  
  heightDF$Column <- factor(heightDF$Column, levels = as.character(sort(as.numeric(levels(heightDF$Column)))))
  heightDF$AA <- factor(heightDF$AA)
  if (is.null(colour)) {
    colour = "taylor"
  }
  if (colour == "clustal") {
    colourPalette = colours_clustal(levels(heightDF$AA))
  } else if (colour == "zappo") {
    colourPalette = colours_zappo(levels(heightDF$AA))
  } else if (colour == "taylor") {
    colourPalette = colours_taylor(levels(heightDF$AA))
  } else if (colour == "mixed") {
    colourPalette = colours_yos(levels(heightDF$AA))
  } else {
    stop("Invalid colour choice for plot_aln()")
  }
  
  ggplot2::ggplot(heightDF, ggplot2::aes(x=Column, y=Height)) + 
    ggplot2::geom_bar(ggplot2::aes(fill = AA), stat = "identity") + 
    ggplot2::scale_fill_manual(values = colourPalette) + 
    ggplot2::theme_bw()+
    ggplot2::theme(text = ggplot2::element_text(size=30),axis.text.x=ggplot2::element_text(angle = 45, hjust=1))
}
