#'Plot a subtree given a node to use as root
#'
#'Takes a node and extracts all descendants of node to create and plot a subtree
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param node label of node to form root of subtree
#'@param fastaDF a dataframe generated by \code{\link{read_fasta}} - only specify this if you want to use a specific dataframe
#'
#'@return a plot of the subtree of interest
#'
#'@examples
#'data(asrStructure)
#'
#'plot_subtree(asrStructure, "N1")
#'
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#'fasta_file <- system.file("extdata", "runASR_aln_full.fa", package="ASR")
#' #alternatively, specify the filename as a string
#' #fasta_file <- "id_aln_full.fa"
#'
#'fastaDF <- read_fasta(NULL, aln_file = fasta_file)
#'plot_subtree(NULL, "N1", fastaDF = fastaDF) # if you want to use a specific dataframe
#'
#' 
#'@export

plot_subtree <- function(asrStructure, node, fastaDF = NULL){
  
  if (!is.null(asrStructure)) {
    if (typeof(asrStructure) != "list") {
      stop(paste("The input for asrStructure: ", asrStructure, ", is not a list therefore not a valid input", sep = ""))
    }
    fastaDF = asrStructure$fastaDF
    if (is.null(fastaDF)) {
      stop("asrStructure does not contain required distribution dataframe. 
            To generate the required files and structures to use this function 
            you will need to run runASR() using Joint inference.")
    }
    if (is.data.frame(fastaDF)) {
      cols <- colnames(fastaDF)
      if (!("Newick" %in% cols && "Label" %in% cols && "Sequence" %in% cols)) {
        stop("The dataframe provided as asrStructure$fastaDF is not correctly formatted. See read_fasta()")
      }
    } else {
      stop(paste("The input for asrStructure$fastaDF is not a dataframe and therefore not a valid input. Input: ", fastaDF, sep = ""))
    }
  } else {
    if(is.null(fastaDF)) {
      stop("You have not provided an asrStructure or specified fastaDF. See read_fasta()")
    } else {
      if (is.data.frame(fastaDF)) {
        cols <- colnames(fastaDF)
        if (!("Newick" %in% cols && "Label" %in% cols && "Sequence" %in% cols)) {
          stop("The dataframe provided as fastaDF is not correctly formatted. See read_fasta()")
        }
      } else {
        stop(paste("The input for fastaDF is not a dataframe and therefore not a valid input. Input: ", fastaDF, sep = ""))
      }
    }
  }
  
  nodeSeq <- fastaDF[fastaDF$Label == node, ]
  if (dim(nodeSeq)[1] == 0) {
    stop(paste("Node ", node, " does not exist in the fasta file containing reconstructed sequences 
from which the Newick strings of subtrees are collected"))
  }
  newickString <- nodeSeq$Newick
  tree = ape::read.tree(file = NULL, text = as.character(newickString))
  plot(tree, show.node.label=TRUE)
  ape::add.scale.bar(0, 0.5)
  
}

#'Save a subtree given a node to use as root
#'
#'Takes a node and extracts all descendants of node to create and saves a subtree
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param node label of node to form root of subtree
#'@param fastaDF a dataframe generated by \code{\link{read_fasta}} - only specify this if you want to use a specific dataframe
#'@param format specifies format to save figure in. Options: "pdf" or "png"
#'@param name what name would you like the figure saved under?
#' 
#'@return saves a plot of the subtree of interest
#'
#'@examples
#'data(asrStructure)
#'
#'save_subtree(asrStructure, "N1")
#'
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#'fasta_file <- system.file("extdata", "runASR_aln_full.fa", package="ASR")
#' #alternatively, specify the filename as a string
#' #fasta_file <- "id_aln_full.fa"
#'
#'fastaDF <- read_fasta(NULL, aln_file = fasta_file)
#'save_subtree(NULL, "N1", fastaDF = fastaDF) # if you want to use a specific dataframe
#'
#'save_subtree(asrStructure, "N1", format = "png", name = "new_name")
#'
#' @export

save_subtree <- function(asrStructure, node, fastaDF = NULL, format = "pdf", name = NULL){
  
  if (!is.null(asrStructure)) {
    if (typeof(asrStructure) != "list") {
      stop(paste("The input for asrStructure: ", asrStructure, ", is not a list therefore not a valid input", sep = ""))
    }
    fastaDF = asrStructure$fastaDF
    if (is.null(fastaDF)) {
      stop("asrStructure does not contain required distribution dataframe. 
            To generate the required files and structures to use this function 
            you will need to run runASR() using Joint inference.")
    }
    if (is.data.frame(fastaDF)) {
      cols <- colnames(fastaDF)
      if (!("Newick" %in% cols && "Label" %in% cols && "Sequence" %in% cols)) {
        stop("The dataframe provided as asrStructure$fastaDF is not correctly formatted. See read_fasta()")
      }
    } else {
      stop(paste("The input for asrStructure$fastaDF is not a dataframe and therefore not a valid input. Input: ", fastaDF, sep = ""))
    }
  } else {
    if(is.null(fastaDF)) {
      stop("You have not provided an asrStructure or specified fastaDF. See read_fasta()")
    } else {
      if (is.data.frame(fastaDF)) {
        cols <- colnames(fastaDF)
        if (!("Newick" %in% cols && "Label" %in% cols && "Sequence" %in% cols)) {
          stop("The dataframe provided as fastaDF is not correctly formatted. See read_fasta()")
        }
      } else {
        stop(paste("The input for fastaDF is not a dataframe and therefore not a valid input. Input: ", fastaDF, sep = ""))
      }
    }
  }
  
  nodeSeq <- fastaDF[fastaDF$Label == node, ]
  if (dim(nodeSeq)[1] == 0) {
    stop(paste("Node ", node, " does not exist in the fasta file containing reconstructed sequences 
from which the Newick strings of subtrees are collected"))
  }
  newickString <- nodeSeq$Newick  
  tree = ape::read.tree(file = NULL, text = as.character(newickString))
  
  if (is.null(name)) {
    name = paste("subtree_", nodeSeq$Label, sep = "")
  }
  
  if (format == "pdf") {
    pdf(paste(name, "_plot.", format, sep=""), width=20, height=20)
    t <- plot(tree, show.node.label=TRUE)
    ape::add.scale.bar(0, 0.5)
    dev.off()
    return(paste("Plot saved as:", name, "_plot.", format, sep=""))
  } else if (format == "png") {
    png(paste(name, "_plot.", format, sep=""), width=2000, height=2000)
    t <- plot(tree, show.node.label=TRUE)
    ape::add.scale.bar(0, 0.5)
    dev.off()
    return(paste("Plot saved as:", name, "_plot.", format, sep=""))
  } else {
    stop("Invalid format for save_tree")
  }
}


#'Generate a vector of node labels given the subtree
#'
#'Takes a node and extracts all descendants of node then returns descendants as a list that could, for example, be passed to \code{\link{plot_aln}}
#'to generate an alignment of the subtree
#'
#'@param asrStructure the named list returned by \code{\link{runASR}} or \code{\link{loadASR}}. Set this to NULL
#'to specify other variables
#'@param node label of node to form root of subtree
#'@param fastaDF a dataframe generated by \code{\link{read_fasta}} - only specify this if you want to use a specific dataframe
#'
#'@return a vector containing all nodes/sequences in the subtree
#'
#'@examples
#'data(asrStructure)
#'
#'get_subtree_sequences(asrStructure, "N1")
#'
#'#if you want to use a specific set of data
#'#retrieve example file stored in the package
#'fasta_file <- system.file("extdata", "runASR_aln_full.fa", package="ASR")
#' #alternatively, specify the filename as a string
#' #fasta_file <- "id_aln_full.fa"
#'
#'fastaDF <- read_fasta(NULL, aln_file = fasta_file)
#'get_subtree_sequences(NULL, "N1", fastaDF = fastaDF) # if you want to use a specific dataframe
#'
#'@export

get_subtree_sequences <- function(asrStructure, node, fastaDF = NULL){
  
  if (!is.null(asrStructure)) {
    if (typeof(asrStructure) != "list") {
      stop(paste("The input for asrStructure: ", asrStructure, ", is not a list therefore not a valid input", sep = ""))
    }
    fastaDF = asrStructure$fastaDF
    if (is.null(fastaDF)) {
      stop("asrStructure does not contain required fasta dataframe. 
            To generate the required files and structures to use this function 
            you will need to run runASR() using Joint inference.")
    }
    if (is.data.frame(fastaDF)) {
      cols <- colnames(fastaDF)
      if (!("Newick" %in% cols && "Label" %in% cols && "Sequence" %in% cols)) {
        stop("The dataframe provided as asrStructure$fastaDF is not correctly formatted. See read_fasta()")
      }
    } else {
      stop(paste("The input for asrStructure$fastaDF is not a dataframe and therefore not a valid input. Input: ", fastaDF, sep = ""))
    }
  } else {
    if(is.null(fastaDF)) {
      stop("You have not provided an asrStructure or specified fastaDF. See read_fasta()")
    } else {
      if (is.data.frame(fastaDF)) {
        cols <- colnames(fastaDF)
        if (!("Newick" %in% cols && "Label" %in% cols && "Sequence" %in% cols)) {
          stop("The dataframe provided as fastaDF is not correctly formatted. See read_fasta()")
        }
      } else {
        stop(paste("The input for fastaDF is not a dataframe and therefore not a valid input. Input: ", fastaDF, sep = ""))
      }
    }
  }

  nodeSeq <- fastaDF[fastaDF$Label == node, ]
  if (dim(nodeSeq)[1] == 0) {
    stop(paste("Node ", node, " does not exist in the fasta file containing reconstructed sequences 
from which the Newick strings of subtrees are collected"))
  }
  newickString <- nodeSeq$Newick
  one <- unlist(strsplit(as.character(newickString), ','))
  two <- gsub("\\(", "", one)
  three <- unlist(strsplit(two, "\\)"))
  four <- unlist(strsplit(three, ":"))
  five <- four[!grepl("\\.", four)]
  five
}




